### ISSUE TITLE
Initial commit?

### ISSUE THREAD

**Issue by NickiHell** [krolaper/aigod#2]

**Comment by krolaper** [comment]
@NickiHell I'm sorry, what are you talking about?

**Comment by NickiHell** [comment]
> @NickiHell I'm sorry, what are you talking about?

You have no code here.

**Comment by krolaper** [comment]
@NickiHell on the main page i have a go to my project with code - aimod project. Here decided not to duplicate.
https://codeberg.org/krolaper/aigod

**Comment by NickiHell** [comment]
> @NickiHell on the main page i have a go to my project with code - aimod project. Here decided not to duplicate. https://codeberg.org/krolaper/aigod

Think about it, I can make you a touch transfer and become a contributor)
